"""Add Admin Tables

Revision ID: 002
Revises: 001
Create Date: 2024-01-28 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=20), nullable=True),
    sa.Column('s3_endpoint', sa.String(length=255), nullable=True),
    sa.Column('s3_bucket', sa.String(length=100), nullable=True),
    sa.Column('s3_region', sa.String(length=50), nullable=True),
    sa.Column('s3_access_key', sa.String(length=100), nullable=True),
    sa.Column('s3_secret_key', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
